# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - run: npm run build --if-present
    - run: npm test

    - name: Automated Version Bump
      id: version-bump
      uses: 'phips28/gh-action-bump-version@master'
      with:
        tag-prefix: 'v'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Project Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Show the current version
      env:
        NEW_VERSION: ${{ steps.package-version.outputs.current-version }}
      run: |
        echo "The new version is $NEW_VERSION"
        echo "Update deployment.yaml"
        sed -i'' "/svadmin:/s/[[:digit:]].[[:digit:]].[[:digit:]]*/$NEW_VERSION/" ".kubernetes/production/deployment.yaml"
        echo "Update README.md"
        sed -i'' "/production-/s/[[:digit:]].[[:digit:]].[[:digit:]]*/$NEW_VERSION/" "README.md"
        echo "grep deployment.yaml" 
        grep 'svadmin:' .kubernetes/production/deployment.yaml || true
        echo "grep README.md"
        grep 'production-' README.md || true
        git add . 
        git commit -m "Bump version (README.md and deployment.yaml) to $NEW_VERSION"
        git push

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/svadmin:${{ steps.package-version.outputs.current-version}}
